version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /usr/app
    environment:
      - NODE_ENV=production
    ports:
      - "8081:8081"
    command: "npm start"
    container_name: node01
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/dev01:/data/db

